# 카프카 서버들의 위치를 설정한다. 기본적으로 로컬호스트를 실행하면서 9092포트를 리스닝하는 카프카 브로커 사용(개발시에는 로컬로 사용[실무시에는 다른 호스트연결])
spring:
  kafka:
    bootstrap-servers:
    - localhost:9092
#    클러스터의 여러 서버를 지정할 수 있다.
#    - kafaka.tacocloud.com:9092
#    - kafaka.tacocloud.com:9093
#    - kafaka.tacocloud.com:9094